# -*- coding: utf-8 -*-
"""Sentencesimilarityproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1md7nImy-fXikMWVtU_epKWyPK2rXIUN2
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-v2')
text1 = input("Enter Text 1: ")
text2 = input("enter Text 2: ")
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)

similarity = util.cos_sim(embedding1, embedding2)

print("/nSimialrity Score:", round(float(similarity),2))

if similarity > 0.75:
  print("similarity level: high")
elif similarity > 0.4:
  print("similarity level: medium")
else:
  print("similarity level: low")

