# -*- coding: utf-8 -*-
"""Text generation code .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJIq66CuhvpcwsIwF-HEKD869gSYMdfx
"""

!pip install transformers torch

from transformers import pipeline

generator=pipeline(
    "text-generation",
    model="gpt2"
)
prompt="Artificial Intelligence in finance will"
result=generator(prompt,max_length=50,num_return_sequences=1)
print("ai generated text:")
print(result[0]['generated_text'])