# -*- coding: utf-8 -*-
"""timetable generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FBkJGGKIpElWBuGWlLPa1tODchFVUF6P
"""

import pandas as pd
import random
print("TIMETABLE GENERATOR\n")
subjects_input = input("enter subjects(comma separted):")
days_input = input("enter days(comma separated):")
periods_per_day = int(input("enter number of periods per day"))
subjects = [s.strip() for s in subjects_input.split(",")if s.strip()]
days = [d.strip() for d in days_input.split(",")if d.strip()]
if len(subjects) == 0 or len(days) == 0 or periods_per_day <=0:
  print("invalid input. please try again.")
else:
  timetable = {}
  for day in days:
    timetable[day] = random.choices(subjects, k=periods_per_day)
  df = pd.DataFrame(timetable)
  df.index = [f"period {i+1}"for i in range(periods_per_day)]
  display(df)
  df.to_csv("Timetable.csv")
  print("\nTimetable saved as timetable.csv")

import pandas as pd
from datetime import datetime

print("MEETING MINUTES GENERATOR\n")
meeting_title = input("enter meeting title:")
date = input("enter meeting date(DD-MM-YYYY):")
time = input("enter meeting time:")
participants = input("enter participants(comma separated):")
agenda = input("enter agenda points(comma separated):")
decisions = input("enter decisions taken(comma separated):")
action_items = input("enter action items(comma separated):")
prepared_by = input("prepared by:")
participants_list = [p.strip() for p in participants.split(",")if p.strip()]
agenda_list = [a.strip() for a in agenda.split(",")if a.strip()]
decisions_list = [d.strip() for d in decisions.split(",")if d.strip()]
actions_list = [a.strip() for a in action_items.split(",")if a.strip()]
minutes={
    "Meeting Title":meeting_title,
    "Date":date,
    "Time":time,
    "Participants":",".join(participants_list),
    "Agenda": ";".join(agenda_list),
    "Decisions Taken": "; ".join(decisions_list),
    "Action Items":"; ".join(actions_list),
    "Prepared By": prepared_by,
    "Generated On":datetime.now().strftime("%d-%m-%Y %H:%M:%S")
}
df=pd.DataFrame(list(minutes.items()),columns=["Field","Details"])
print("\n meeting minutes generated successfully\n")
display(df)
df.to_csv("meeting_minutes.csv",index=False)
print("\n file saved as meeting_minutes.csv")